**Matrix Tensors**

In [ ]:
import numpy as np

#buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[1, 2, 3],[4, 5, 6]])
print("Matrix X =")
print(X)

# tampilkan ukuran dari matrix X
print("Ukuran matrix X =", X.shape)

# tampilkan seluruh elemen dari kolom pertama
print("Kolom pertama matrix X =", X[:,0])

# tampilkan seluruh elemen dari baris kedua
print("Baris kedua matrix X =", X[1, :])


Matrix X =
[[1 2 3]
 [4 5 6]]
Ukuran matrix X = (2, 3)
Kolom pertama matrix X = [1 4]
Baris kedua matrix X = [4 5 6]


In [ ]:
import torch

#buat matrix X berukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[25, 0], [1, 20], [5, 50]])
print(X_pt)

# tampilkan ukuran dari matrix X dengan pytorch
print("Ukuran matrix X =", X_pt.shape)

# tampilkan seluruh elemen dari kolom pertama dengan pytorch
print("Kolom pertama matrix X =", X_pt[:,0])

# tampilkan seluruh elemen dari baris kedua dengan pytorch
print("Baris kedua matrix X =", X_pt[1, :])

tensor([[25,  0],
        [ 1, 20],
        [ 5, 50]])
Ukuran matrix X = torch.Size([3, 2])
Kolom pertama matrix X = tensor([25,  1,  5])
Baris kedua matrix X = tensor([ 1, 20])


In [ ]:
import tensorflow as tf

# buat matrix X_tf berukuran 2x3
X_tf = tf.constant([[2, 4, 6],[1, 3, 5]])

print("Matrix X_tf =")
print(X_tf)

# tampilkan ukuran dari matrix X_tf
print("Ukuran matrix X_tf =", X_tf.shape)

# tampilkan seluruh elemen dari kolom pertama
print("Kolom pertama matrix X_tf =", X_tf[:, 0])


# tampilkan seluruh elemen dari baris kedua
print("Baris kedua matrix X_tf =", X_tf[1, :])


Matrix X_tf =
tf.Tensor(
[[2 4 6]
 [1 3 5]], shape=(2, 3), dtype=int32)
Ukuran matrix X_tf = (2, 3)
Kolom pertama matrix X_tf = tf.Tensor([2 1], shape=(2,), dtype=int32)
Baris kedua matrix X_tf = tf.Tensor([1 3 5], shape=(3,), dtype=int32)
