**Vectors and Vector Transposition**

In [ ]:
import numpy as np

#buat vector x dengan ukuran 3x1
x_vector = np.array([[1],[2],[3]])
print("x= ", x_vector)

#hitung panjang vector x
print("Panjang vector x= ", len(x_vector))

#tampilkan ukuran vector x
print("Ukuran vector x= ", x_vector.shape)

#tampilkan tipe data dari x
print("Tipe data x=", type(x_vector))

# Akses elemen pertama dari vector x
print("Elemen pertama vector x =", x_vector[0])

#tampilkan tipe data elemen pertama dari vector x
print("Tipe data elemen pertama =", type(x_vector[0][0]))

#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x_vector.T
print("Transpose vector x= ", x_t)

#tampilkan ukuran dari vector x_t
print("Ukuran vector x_t= ", x_t.shape)

#lakukan transpose pada vector y dan simpan pada variabel y_t
y_vector = np.array([[4],[5],[6],[7]])
print("y=", y_vector)
y_t = y_vector.T
print("Transpose vector y=", y_t)

#tampilkan ukuran dari vector y_t
print("Ukuran vector y_t= ", y_t.shape)

x=  [[1]
 [2]
 [3]]
Panjang vector x=  3
Ukuran vector x=  (3, 1)
Tipe data x= <class 'numpy.ndarray'>
Elemen pertama vector x = [1]
Tipe data elemen pertama = <class 'numpy.int64'>
Transpose vector x=  [[1 2 3]]
Ukuran vector x_t=  (1, 3)
y= [[4]
 [5]
 [6]
 [7]]
Transpose vector y= [[4 5 6 7]]
Ukuran vector y_t=  (1, 4)


In [ ]:
import torch

#buat vector x dengan ukuran 3x1 dengan pytorch
xpt_vector = torch.tensor([[2], [4], [6]])
print("x= ", xpt_vector)

#lakukan transpose pada vector x dan simpan pada variabel x_t dengan pytorch
x_t = xpt_vector.t()
print("Transpose vector x= ", x_t)

#tampilkan ukuran dari vector x_t dengan pytorch
print("Ukuran vector x_t= ", x_t.size())

#lakukan transpose pada vector y dan simpan pada variabel y_t dengan pytorch
ypt_vector = torch.tensor([[6], [7], [8], [9]])
print("y=", ypt_vector)
y_t = ypt_vector.t()
print("Transpose vector y=", y_t)

#tampilkan ukuran dari vector y_t dengan pytorch
print("Ukuran vector y_t= ", y_t.size())

x=  tensor([[2],
        [4],
        [6]])
Transpose vector x=  tensor([[2, 4, 6]])
Ukuran vector x_t=  torch.Size([1, 3])
y= tensor([[6],
        [7],
        [8],
        [9]])
Transpose vector y= tensor([[6, 7, 8, 9]])
Ukuran vector y_t=  torch.Size([1, 4])


In [ ]:
import tensorflow as tf

#buat vector x dengan ukuran 3x1 dengan tensorflow
xtf_vector = tf.constant([[2], [3], [5]])
print("x= ", xtf_vector)

#lakukan transpose pada vector x dan simpan pada variabel x_t dengan tensorflow
x_t = tf.transpose(xtf_vector)
print("Transpose vector x= ", x_t)

#tampilkan ukuran dari vector x_t dengan tensorflow
print("Ukuran vector x_t= ", x_t.shape)

#lakukan transpose pada vector y dan simpan pada variabel y_t dengan tensorflow
ytf_vector = tf.constant([[1], [0], [0], [1]])
print("y=", ytf_vector)
y_t = tf.transpose(ytf_vector)
print("Transpose vector y=", y_t)

#tampilkan ukuran dari vector y_t dengan tensorflow
print("Ukuran vector y_t= ", y_t.shape)

x=  tf.Tensor(
[[2]
 [3]
 [5]], shape=(3, 1), dtype=int32)
Transpose vector x=  tf.Tensor([[2 3 5]], shape=(1, 3), dtype=int32)
Ukuran vector x_t=  (1, 3)
y= tf.Tensor(
[[1]
 [0]
 [0]
 [1]], shape=(4, 1), dtype=int32)
Transpose vector y= tf.Tensor([[1 0 0 1]], shape=(1, 4), dtype=int32)
Ukuran vector y_t=  (1, 4)
