MEMBUAT MATRIX UKURAN 3X3 DAN MENGHITUNG NILAI FROBENIUS NORM MENGGUNAKAN NUMPY, PYTORCH DAN TENSORFLOW

NUMPY

Matrix ukuran 3X3

In [ ]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Menghitung nilai matrix ukuran 3X3

In [ ]:
np.linalg.norm(A)


np.float64(16.881943016134134)

PYTORCH

Matrix ukuran 3X3

In [1]:
import torch

A_pt = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
A_pt


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Menghitung nilai matrix ukuran 3X3

In [ ]:
torch.norm(A_pt)

tensor(16.8819)

TENSORFLOW

Matrix ukuran 3X3

In [ ]:
import tensorflow as tf

A_tf = tf.Variable([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
A_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

Menghitung nilai matrix ukuran 3X3

In [ ]:
tf.norm(A_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=16.881942749023438>