MEMBUAT MATRIX A DENGAN UKURAN 2X3 DAN VECTOR B BERUKURAN 3X1 MENGGUNAKAN NUMPY, PYTORCH, DAN TENSORFLOW

NUMPY

Matrix ukuran 2X3

In [3]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

Vector ukuran 3X1

In [4]:
b = np.array([[7], [8], [9]])
b

array([[7],
       [8],
       [9]])

PYTORCH

Matrix ukuran 2X3

In [5]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
A_pt

tensor([[1, 2, 3],
        [4, 5, 6]])

Vector ukuran 3X1

In [6]:
b_pt = torch.tensor([[7], [8], [9]])
b_pt

tensor([[7],
        [8],
        [9]])

TENSORFLOW

Matrix ukuran 2X3

In [7]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
A_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Vector ukuran 3X1

In [8]:
import tensorflow as tf

b_tf = tf.Variable([[7], [8], [9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[7],
       [8],
       [9]], dtype=int32)>

MENAMPILKAN UKURAN MATRIX A DAN VECTOR B

NUMPY

In [9]:
print("Ukuran A:", A.shape)
print("Ukuran b:", b.shape)

Ukuran A: (2, 3)
Ukuran b: (3, 1)


PYTORCH

In [10]:
print("Ukuran A_pt:", A_pt.shape)
print("Ukuran b_pt:", b_pt.shape)

Ukuran A_pt: torch.Size([2, 3])
Ukuran b_pt: torch.Size([3, 1])


TENSORFLOW

In [11]:
print("Ukuran A_tf:", A_tf.shape)
print("Ukuran b_tf:", b_tf.shape)

Ukuran A_tf: (2, 3)
Ukuran b_tf: (3, 1)


MENGKALIKAN MATRIX A DENGAN VECTOR B

In [12]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8], [9]])

np.dot(A, b)

array([[ 50],
       [122]])

MENGKALIKAN MATRIX A_PT DENGAN VECTOR B_PT

In [13]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
b_pt = torch.tensor([[7], [8], [9]])

torch.matmul(A_pt, b_pt)


tensor([[ 50],
        [122]])

MENGKALIKAN MATRIX A_TF DENGAN VECTOR B_TF



In [14]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
b_tf = tf.Variable([[7], [8], [9]])

tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 50],
       [122]], dtype=int32)>

MEMBUAT MATRIX B DENGAN UKURAN 3X3 MENGGUNAKAN NUMPY

In [15]:
import numpy as np

B = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MEMBUAT MATRIX B_PT DENGAN UKURAN 3X3 MENGGUNAKAN PYTORCH


In [16]:
import torch

B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

MEMBUAT MATRIX B_TF DENGAN UKURAN 3X3 MENGGUNAKAN TENSORFLOW

In [17]:
import tensorflow as tf

B_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

MENGKALIKAN MATRIX A DENGAN MATRIX B

In [18]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

np.dot(A, B)


array([[30, 36, 42],
       [66, 81, 96]])

MENGKALIKAN MATRIX A_PT DENGAN MATRIX B_PT

In [19]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

torch.matmul(A_pt, B_pt)

tensor([[30, 36, 42],
        [66, 81, 96]])

MENGKALIKAN MATRIX A_TF DENGAN MATRIX B_TF

In [20]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
B_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

MEMBUKTIKAN PERKALIAN MATRIX BERSIFAT KOMUTATIF (AB=BA)

In [25]:
import numpy as np
import torch
import tensorflow as tf

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
AB_np = np.dot(A, B)
print("NUMPY")
print("A x B:\n", AB_np)
print("B x A: tidak dapat dikalikan")


A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
AB_pt = torch.matmul(A_pt, B_pt)
print("\nPYTORCH")
print("A x B:\n", AB_pt.numpy())
print("B x A: tidak dapat dikalikan")


A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
B_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
AB_tf = tf.matmul(A_tf, B_tf)
print("\nTENSORFLOW")
print("A x B:\n", AB_tf.numpy())
print("B x A: tidak dapat dikalikan")

NUMPY
A x B:
 [[30 36 42]
 [66 81 96]]
B x A: tidak dapat dikalikan

PYTORCH
A x B:
 [[30 36 42]
 [66 81 96]]
B x A: tidak dapat dikalikan

TENSORFLOW
A x B:
 [[30 36 42]
 [66 81 96]]
B x A: tidak dapat dikalikan
