MEMBUAT MATRIX A DENGAN UKURAN 2X3 DAN VECTOR B BERUKURAN 3X1 MENGGUNAKAN NUMPY, PYTORCH, DAN TENSORFLOW

NUMPY

Matrix ukuran 2X3

In [61]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

Vector ukuran 3X1

In [62]:
b = np.array([[7], [8], [9]])
b

array([[7],
       [8],
       [9]])

PYTORCH

Matrix ukuran 2X3

In [63]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
A_pt

tensor([[1, 2, 3],
        [4, 5, 6]])

Vector ukuran 3X1

In [64]:
b_pt = torch.tensor([[7], [8], [9]])
b_pt

tensor([[7],
        [8],
        [9]])

TENSORFLOW

Matrix ukuran 2X3

In [65]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
A_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Vector ukuran 3X1

In [66]:
import tensorflow as tf

b_tf = tf.Variable([[7], [8], [9]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[7],
       [8],
       [9]], dtype=int32)>

MENAMPILKAN UKURAN MATRIX A DAN VECTOR B

NUMPY

In [67]:
print("Ukuran A:", A.shape)
print("Ukuran b:", b.shape)

Ukuran A: (2, 3)
Ukuran b: (3, 1)


PYTORCH

In [68]:
print("Ukuran A_pt:", A_pt.shape)
print("Ukuran b_pt:", b_pt.shape)

Ukuran A_pt: torch.Size([2, 3])
Ukuran b_pt: torch.Size([3, 1])


TENSORFLOW

In [69]:
print("Ukuran A_tf:", A_tf.shape)
print("Ukuran b_tf:", b_tf.shape)

Ukuran A_tf: (2, 3)
Ukuran b_tf: (3, 1)


MENGKALIKAN MATRIX A DENGAN VECTOR B

In [70]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8], [9]])

np.dot(A, b)

array([[ 50],
       [122]])

MENGKALIKAN MATRIX A_PT DENGAN VECTOR B_PT

In [71]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
b_pt = torch.tensor([[7], [8], [9]])

torch.matmul(A_pt, b_pt)


tensor([[ 50],
        [122]])

MENGKALIKAN MATRIX A_TF DENGAN VECTOR B_TF



In [72]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
b_tf = tf.Variable([[7], [8], [9]])

tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 50],
       [122]], dtype=int32)>

MEMBUAT MATRIX B DENGAN UKURAN 3X3 MENGGUNAKAN NUMPY

In [73]:
import numpy as np

B = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

MEMBUAT MATRIX B_PT DENGAN UKURAN 3X3 MENGGUNAKAN PYTORCH


In [75]:
import torch

B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

MEMBUAT MATRIX B_TF DENGAN UKURAN 3X3 MENGGUNAKAN TENSORFLOW

In [76]:
import tensorflow as tf

B_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

MENGKALIKAN MATRIX A DENGAN MATRIX B

In [77]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2, 3], [4, 5, 6],  [7, 8, 9]])

np.dot(A, B)


array([[30, 36, 42],
       [66, 81, 96]])

MENGKALIKAN MATRIX A_PT DENGAN MATRIX B_PT

In [78]:
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

torch.matmul(A_pt, B_pt)

tensor([[30, 36, 42],
        [66, 81, 96]])

MENGKALIKAN MATRIX A_TF DENGAN MATRIX B_TF

In [79]:
import tensorflow as tf

A_tf = tf.constant([[1, 2, 3], [4, 5, 6]])
B_tf = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>

MEMBUKTIKAN PERKALIAN MATRIX BERSIFAT KOMUTATIF (AB=BA)

NUMPY

In [80]:
B_pt = torch.from_numpy(B)
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [81]:
B_pt = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).T
B_pt

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

TORCH

In [85]:
torch.matmul(A_pt, B_pt)

tensor([[ 14,  32,  50],
        [ 32,  77, 122]])

TENSORFLOW

In [83]:
import tensorflow as tf

B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [84]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]], dtype=int32)>