1. Buat matrix X ukuran 2x2 menggunakan numpy

In [60]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import torch

In [61]:
X = np.array([[6, 2], [10, -5]])
X

array([[ 6,  2],
       [10, -5]])

2. Buat invers dari matrix X dan beri nama Xinv menggunakan numpy

In [62]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 0.1 ,  0.04],
       [ 0.2 , -0.12]])

3. Kalikan X dengan Xinv menggunakan numpy

In [63]:
np.dot(Xinv, X)

array([[ 1.00000000e+00,  4.16333634e-17],
       [-5.55111512e-17,  1.00000000e+00]])

4. Selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

Numpy

In [64]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [65]:
Y = np.array([4, -7])
Y

array([ 4, -7])

In [66]:
solvingNP = np.linalg.solve(X, Y)
solvingNP

array([-1.,  4.])

Tensorflow

In [67]:
X = tf.constant([[4., 2.], [-5., -3.]])
X

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 4.,  2.],
       [-5., -3.]], dtype=float32)>

In [68]:
Y = tf.constant([[4.], [-7.]])
Y

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[ 4.],
       [-7.]], dtype=float32)>

In [69]:
solvingTF = tf.linalg.solve(A, B)
solvingTF

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.99999946],
       [ 3.999999  ]], dtype=float32)>

Pytorch

In [72]:
X = torch.tensor([[4., 2.], [-5., -3.]])
X

tensor([[ 4.,  2.],
        [-5., -3.]])

In [73]:
Y = torch.tensor([[4.], [-7.]])
Y

tensor([[ 4.],
        [-7.]])

In [76]:
solvingPT = torch.linalg.solve(X, Y)
solvingPT

tensor([[-1.],
        [ 4.]])