1. lakukan perhitungan soal excercise menggunakan collab

In [1]:
import torch

In [3]:
#1

M_q = torch.tensor([[0,1,2], [3,4,5],[6,7,8]])
N_q = torch.tensor([[-1],[1],[2]])

print(torch.matmul(M_q, N_q))

tensor([[ 5],
        [11],
        [17]])


In [8]:
#2

I = torch.tensor([[1, 0, 0],[0, 1, 0],[0, 0, 1]])

torch.matmul(I, N_q)

tensor([[-1],
        [ 1],
        [ 2]])

In [6]:
#3

O_q = torch.tensor([[-1,0], [1,1], [-2,2]])
torch.matmul(M_q, O_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])