1. Buat matrix X ukuran 2x2 menggunakan numpy

In [77]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import torch as pt

In [78]:
X = np.array([[6, 2], [10, -5]])
X

array([[ 6,  2],
       [10, -5]])

2. Buat invers dari matrix X dan beri nama Xinv menggunakan numpy

In [79]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 0.1 ,  0.04],
       [ 0.2 , -0.12]])

3. Kalikan X dengan Xinv menggunakan numpy

In [80]:
np.dot(Xinv, X)

array([[ 1.00000000e+00,  4.16333634e-17],
       [-5.55111512e-17,  1.00000000e+00]])

4. Selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch

Numpy

In [87]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [88]:
Y = np.array([4, -7])
Y

array([ 4, -7])

In [89]:
solvingNP = np.linalg.solve(X, Y)
solvingNP

array([-1.,  4.])

Tensorflow

In [90]:
X = tf.Variable([[4, 2], [-5, -3]], dtype=tf.float64)
X

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float64, numpy=
array([[ 4.,  2.],
       [-5., -3.]])>

In [91]:
Y = tf.Variable([[4], [-7]], dtype=tf.float64)
Y

<tf.Variable 'Variable:0' shape=(2, 1) dtype=float64, numpy=
array([[ 4.],
       [-7.]])>

In [92]:
solvingTF = tf.linalg.solve(X, Y)
solvingTF

<tf.Tensor: shape=(2, 1), dtype=float64, numpy=
array([[-1.],
       [ 4.]])>

Pytorch

In [93]:
X = pt.tensor([[4, 2], [-5, -3]], dtype=pt.float32)
X

tensor([[ 4.,  2.],
        [-5., -3.]])

In [94]:
Y = pt.tensor([[4], [-7]], dtype=pt.float32)
Y

tensor([[ 4.],
        [-7.]])

In [95]:
solvingPT = pt.linalg.solve(X, Y)
solvingPT

tensor([[-1.],
        [ 4.]])