1. lakukan perhitungan soal excercise menggunakan collab

In [ ]:
import torch

In [ ]:
M_q = torch.tensor([[1, 5, 3], [5, 23, 8], [3, 8, 17]])
M_q

tensor([[ 1,  5,  3],
        [ 5, 23,  8],
        [ 3,  8, 17]])

In [ ]:
V_q = torch.tensor([[-2, 3, -1], [1, 0, 2]]).T
V_q

tensor([[-2,  1],
        [ 3,  0],
        [-1,  2]])

In [ ]:
torch.matmul(M_q, V_q)

tensor([[10,  7],
        [51, 21],
        [ 1, 37]])