1. Buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

In [1]:
import numpy as np

In [3]:
X_sym = np.array([[1, 5, 3], [5, 23, 8], [3, 8, 17]])
X_sym

array([[ 1,  5,  3],
       [ 5, 23,  8],
       [ 3,  8, 17]])

In [4]:
X_sym.T

array([[ 1,  5,  3],
       [ 5, 23,  8],
       [ 3,  8, 17]])

In [5]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

2. Menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4

In [6]:
import torch

In [7]:
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

3. Menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1

In [8]:
x_pt = torch.tensor([7, 23, 8, 5])
x_pt

tensor([ 7, 23,  8,  5])

4. Kalikan matrix I dengan vector b_pt

In [9]:
torch.matmul(I, x_pt)

tensor([ 7, 23,  8,  5])