Basic Tensor Arithmetic (The Hadamard Product)

In [3]:
import numpy as np

In [10]:
import torch

In [13]:
import tensorflow as tf

No. 1

buat matrix X dengan ukuran 2x3 menggunakan numpy

In [7]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch

In [11]:
X_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])
X_pt

tensor([[ 7,  8,  9],
        [10, 11, 12]])

buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [35]:
X_tf = tf.Variable([[13, 14, 15], [16, 17, 18]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>

No. 2

 lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar

In [36]:
X*3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[39, 42, 45],
       [48, 51, 54]], dtype=int32)>

In [37]:
X_pt*3

tensor([[21, 24, 27],
        [30, 33, 36]])

In [38]:
X_tf*3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[39, 42, 45],
       [48, 51, 54]], dtype=int32)>

lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar

In [39]:
X+3

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
X_pt+3

tensor([[10, 11, 12],
        [13, 14, 15]])

In [41]:
X_tf+3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[16, 17, 18],
       [19, 20, 21]], dtype=int32)>

lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar

In [42]:
X-3

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [44]:
X_pt-3

tensor([[4, 5, 6],
        [7, 8, 9]])

In [43]:
X_tf-3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15]], dtype=int32)>

No. 2

buat matrix Y dengan ukuran 2x3 menggunakan numpy

In [45]:
Y = np.array([[1, 2, 3], [4, 5, 6]])
Y

array([[1, 2, 3],
       [4, 5, 6]])

buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch

In [46]:
Y_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])
Y_pt

tensor([[ 7,  8,  9],
        [10, 11, 12]])

buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow

In [47]:
Y_tf = tf.Variable([[13, 14, 15], [16, 17, 18]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>

kalikan matrix X dengan Y

In [49]:
X*Y

array([[ 1,  4,  9],
       [16, 25, 36]])

kalikan matrix X_pt dengan Y_pt

In [50]:
X_pt*Y_pt

tensor([[ 49,  64,  81],
        [100, 121, 144]])

kalikan matrix X_tf dengan Y_tf

In [51]:
X_tf*Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[169, 196, 225],
       [256, 289, 324]], dtype=int32)>