Tensor Reduction

No. 1

In [2]:
import numpy as np

In [3]:
import torch

In [4]:
import tensorflow as tf

buat matrix X dengan ukuran 2x3 menggunakan numpy

In [5]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum

In [6]:
X.sum()

np.int64(21)

buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [7]:
X_tf = tf.Variable([[13, 14, 15], [16, 17, 18]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[13, 14, 15],
       [16, 17, 18]], dtype=int32)>

No. 2

hitung hasil penjumlahan seluruh elemen matrix X

In [8]:
X.sum()

np.int64(21)

hitung hasil penjumlahan seluruh elemen matrix X_pt

In [9]:
X_pt = torch.tensor([[7, 8, 9], [10, 11, 12]])
torch.sum(X_pt)

tensor(57)

hitung hasil penjumlahan seluruh elemen matrix X_tf

In [10]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=93>

No. 3

hitung hasil penjumlahan matrix X berdasarkan row nya

In [12]:
X.sum(axis=0)

array([5, 7, 9])

hitung hasil penjumlahan matrix X_pt berdasarkan row nya

In [14]:
torch.sum(X_pt, 0)

tensor([17, 19, 21])

hitung hasil penjumlahan matrix X_tf berdasarkan row nya

In [16]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([29, 31, 33], dtype=int32)>

No. 4

hitung hasil penjumlahan matrix X berdasarkan kolom nya

In [17]:
X.sum(axis=1)

array([ 6, 15])

hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya

In [18]:
torch.sum(X_pt, 1)

tensor([24, 33])

hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya

In [19]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([42, 51], dtype=int32)>

No. 5

hitung nilai minimal dari matrix X, X_pt dan X_tf:

In [26]:
print(f"Minimal X : {X.min()}")
print(f"Minimal X_pt : {torch.min(X_pt)}")
print(f"Minimal f X_tf : {tf.reduce_min(X_tf)}")

Minimal X : 1
Minimal X_pt : 7
Minimal f X_tf : 13


hitung nilai maksimal dari matrix X, X_pt dan X_tf

In [28]:
print(f"Maksimal X : {X.max()}")
print(f"Maksimal X_pt : {torch.max(X_pt)}")
print(f"Maksimal f X_tf : {tf.reduce_max(X_tf)}")

Maksimal X : 6
Maksimal X_pt : 12
Maksimal f X_tf : 18


hitung nilai rata-rata dari matrix X, X_pt dan X_tf

In [31]:
print(f"Rata-rata X : {X.mean()}")
print(f"Rata-rata X_pt : {torch.mean(X_pt.float())}")
print(f"Rata-rata X_tf : {tf.reduce_mean(tf.cast(X_tf, tf.float32))}")

Rata-rata X : 3.5
Rata-rata X_pt : 9.5
Rata-rata X_tf : 15.5


No. 6

hitung hasil perkalian seluruh elemen matrix X

In [32]:
X.prod()

np.int64(720)

hitung hasil perkalian seluruh elemen matrix X_pt

In [33]:
X_pt.prod()

tensor(665280)

hitung hasil perkalian seluruh elemen matrix X_tf

In [35]:
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=13366080>