**Tensor Transposition**

In [4]:
import numpy as np
import torch
import tensorflow as tf

#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix X:")
print(X)

#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Matrix X_pt:")
print(X_pt)

#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.variable([[1, 2, 3], [4, 5, 6]])
print("Matrix X_tf:")
print(X_tf)

Matrix X:
[[1 2 3]
 [4 5 6]]
Matrix X_pt:
tensor([[1, 2, 3],
        [4, 5, 6]])
Matrix X_tf:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
#lakukan transpose pada matrix X, X_pt dan X_tf"

#transpose matrix X
print("Transpose matrix X:")
print(X.T)

#transpose matrix X_pt
print("Transpose matrix X_pt:")
print(X_pt.T)

#transpose matrix X_tf
print("Transpose matrix X_tf:")
print(tf.transpose(X_tf))

Transpose matrix X:
[[1 4]
 [2 5]
 [3 6]]
Transpose matrix X_pt:
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Transpose matrix X_tf:
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
