In [5]:
import numpy as np
import torch
import tensorflow as tf

Nomor 1

buat vector x dan y dengan ukuran 1x3 menggunakan numpy

In [6]:
# 1. buat vector x dan y dengan ukuran 1x3
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [7]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

buat vector x_pt dan y_pt dengan ukuran 1x3 menggunakan pytorch

In [8]:
x_pt = torch.tensor([1, 2, 3])
x_pt

tensor([1, 2, 3])

In [9]:
y_pt = torch.tensor([4, 5, 6])
y_pt

tensor([4, 5, 6])

buat vector x_tf dan y_tf dengan ukuran 1x3 menggunakan tensorflow

In [19]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

In [18]:
y_tf = tf.Variable([0, 1, 2])
y_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

Nomor 2

hitung perkalian dot product antara vector x dan vector y

In [10]:
np.dot(x, y)

np.int64(32)

hitung perkalian dot product antara vector x_pt dan vector y_pt

In [16]:
torch.dot(x_pt, y_pt)

tensor(32)

hitung perkalian dot product antara vector x_tf dan vector y_tf

In [20]:
tf.reduce_sum(tf.multiply(x_tf, y_tf))

<tf.Tensor: shape=(), dtype=int32, numpy=12>

Nomorr 3

lakukan perhitungan excercise menggunakan collab

exercise 1

In [26]:
# Mendefinisikan Matrix Y ukuran 2x4
Y = np.array([[42, 4, 7, 99],
              [-99, -3, 17, 22]])
# Menghitung Transpose dari Matrix Y
Y_transpose = Y.T
print(Y_transpose)

[[ 42 -99]
 [  4  -3]
 [  7  17]
 [ 99  22]]


exercise 2

In [27]:
# Mendefinisikan dua matriks 2x2
matriks_1 = np.array([[25, 10],
                      [-2, 1]])

matriks_2 = np.array([[-1, 7],
                      [10, 8]])
# Menghitung Hadamard Product (Element-wise multiplication)
hadamard_res = matriks_1 * matriks_2
print(hadamard_res)

[[-25  70]
 [-20   8]]


exercise 3

In [28]:
# Mendefinisikan vektor w dan x
w = np.array([-1, 2, -2])
x_val = np.array([5, 10, 0])

# Menghitung Dot Product
dot_wx = np.dot(w, x_val)
print(dot_wx)

15
